# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=50)),
                ('PassWord', models.CharField(max_length=50)),
                ('User_Mail', models.CharField(max_length=250)),
            ],
        ),
    ]
